name: marketstack_demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  http: ^0.13.5
  http_interceptor: ^1.0.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  equatable: ^2.0.5
  iconify_flutter: ^0.0.5
  page_transition: ^2.0.9
  connectivity_plus: ^3.0.2
  flutter_staggered_animations: ^1.1.1
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true